version: "2.2"

services:

  squid:
    build:
      context: "./squid"
      args:
        SQUID_VERSION: 6.1
    restart: always
    ports:
      - "3128:3128"
      - "3129:3129"      
    volumes:
      - ./squid/certs:/etc/squid/ssl_cert
      - ./squid/squid.conf:/etc/squid/squid.conf
