name: Package Cleanup

on:
  workflow_dispatch

jobs:
  cleanup-packages:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v4
        with: 
          package-name: 'docker-squid'
          package-type: 'container'
          min-versions-to-keep: 1
          delete-only-untagged-versions: 'true'
